version: '2'
services:
  grafana-setup:
    image: adopteunops/grafana-rancher-setup:latest
    stdin_open: true
    tty: true
    external_links:
    - "prometheus/grafana:grafana"
    labels:
      io.rancher.container.start_once: 'true'
