version: '2'
services:
  grafana-setup:
    metadata:
      datasources: |
        [
          {
            "name": "prometheus",
            "value": {
              "id": "prometheus",
              "orgId": 1,
              "name": "prometheus",
              "type": "prometheus",
              "typeLogoUrl": "",
              "access": "proxy",
              "url": "http://prometheus:9090",
              "basicAuth": false,
              "basicAuthUser": "",
              "basicAuthPassword": "",
              "withCredentials": false,
              "isDefault": false,
              "jsonData": {}
            }
          }
        ]
      dashboards: |
        [
          {
            "name": "mydashboard",
            "value": {
                      "dashboard": {
                        "id": null,
                        "title": "Dummy Event",
                        "tags": [],
                        "style": "dark",
                        "timezone": "browser",
                        "editable": true,
                        "hideControls": false,
                        "sharedCrosshair": false,
                        "rows": [
                          {
                            "collapse": false,
                            "editable": true,
                            "height": "250px",
                            "panels": [
                              {
                                "content": "# Dummy dashboard",
                                "editable": true,
                                "error": false,
                                "id": 1,
                                "isNew": true,
                                "mode": "markdown",
                                "span": 12,
                                "title": "Panel Title",
                                "type": "text"
                              }
                            ],
                            "title": "Row"
                          }
                        ],
                        "time": {
                          "from": "now-6h",
                          "to": "now"
                        },
                        "timepicker": {
                          "refresh_intervals": [
                            "5s",
                            "10s",
                            "30s",
                            "1m",
                            "5m",
                            "15m",
                            "30m",
                            "1h",
                            "2h",
                            "1d"
                          ],
                          "time_options": [
                            "5m",
                            "15m",
                            "1h",
                            "6h",
                            "12h",
                            "24h",
                            "2d",
                            "7d",
                            "30d"
                          ]
                        },
                        "templating": {
                          "list": []
                        },
                        "annotations": {
                          "list": []
                        },
                        "schemaVersion": 12,
                        "version": 1,
                        "links": [],
                        "gnetId": null
                      }
                    }
          }
        ]
      notifications: |
        [
          {
            "name": "email",
            "value": {
                        "type": "email",
                        "settings": {
                          "httpMethod": "POST",
                          "autoResolve": true,
                          "uploadImage": true,
                          "addresses": "myadress@domain.com"
                        },
                        "isDefault": true,
                        "name": "email"
                      }
          }
        ]
